import {AiFillStar} from "react-icons/ai"
export const Product=[
    {
        
      id:1,
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      title: "Nike Air Monarch IV",
      star: <AiFillStar className="ratings-start" style={{Color:"gold"}} />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 699,
      company: "Nike",
      color: "white",
      category: "sneakers",
      gender:'men',
      quantity:1,
      stock:6                                                                                                                                                                                                                                                     
    },
    {
      id:2,
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 700,
      company: "Puma",
      color: "red",
      category: "sneakers",
      gender:'men',
      quantity:1,
      stock:8
    },
  
    {
      id:3,
      img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      title: "Nike Waffle Sneaker",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 800,
      company: "Nike",
      color: "green",
      category: "sneakers",
      gender:'men',
      quantity:1,
      stock:10
      
    },
    {
      id:4,
      img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      title: "Adidas Running Shoe",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 620,
      company: "Adidas",
      color: "black",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:8
    },
  
    {
      id:5,
      img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      title: "Knit Ballet Flat",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 500,
      company: "Adidas",
      color: "black",
      category: "flats",
      gender:"wommen",
      quantity:1,
      stock:8
    },
  
    {
      id:6,
      img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      title: "Loafer Flats",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 500,
      company: "Vans",
      color: "white",
      category: "flats",
      gender:"wommen",
      quantity:1,
      stock:8
    },
  
    {
      id:7,
      img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
      title: "Nike Zoom Freak",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 200,
      company: "Nike",
      color: "green",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:11
    },
  
    {
      id:8,
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      title: "Adidas Men's Sneaker",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 2000,
      company: "Adidas",
      color: "blue",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:4
    },
  
    {
      id:9,
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      title: "PUMA BLACK-OCE",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "15000",
      newPrice: 1500,
      company: "Puma",
      color: "green",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:12
    },
    {
      id:10,
      img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
      title: "Pacer Future Sneaker",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 1500,
      company: "Puma",
      color: "red",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:5
    },
    {
      id:11,
      img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
      title: "Unisex-Adult Super",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: 14000,
      newPrice: "15000",
      company: "Puma",
      color: "black",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:9
    },
    {
      id:12,
      img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL.AC_UX575.jpg",
      title: "Roma Basic Sneaker",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: 1400,
      newPrice: "15000",
      company: "Puma",
      color: "white",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:7
    },
    {
      id:13,
      img: "https://m.media-amazon.com/images/I/7128-af7joL.AC_UY575.jpg",
      title: "Pacer Future Doubleknit",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice:14000,
      newPrice: "2500",
      company: "Puma",
      color: "black",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:15
    },
  
    { id:14,
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS.AC_UX575.jpg",
      title: "Fusion Evo Golf Shoe",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 1000,
      company: "Puma",
      color: "green",
      category: "sneakers",
      gender:"men",
      quantity:1,
      stock:16
      
    },
    {
      id:15,
      img: "https://m.media-amazon.com/images/I/719gdz8lsTS.AC_UX575.jpg",
      title: "Rainbow Chex Skate",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 10000,
      company: "Vans",
      color: "red",
      category: "flats",
      gender:"men",
      quantity:1,
      stock:10
    },
    {
      id:16,
      img: "https://m.media-amazon.com/images/I/71gpFHJlnoL.AC_UX575.jpg",
      title: "Low-Top Trainers",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice:"14000",
      newPrice: "1800",
      company: "Vans",
      color: "white",
      category: "sandals",
      gender:"men",
      quantity:1,
      stock:12
    },
    {
      id:17,
      img: "https://m.media-amazon.com/images/I/71pf7VFs9CL.AC_UX575.jpg",
      title: "Vans Unisex Low-Top",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice:"14000",
      newPrice: 1350,
      company: "Vans",
      color: "blue",
      category: "sandals",
      gender:"men",
      quantity:1,
      stock:15
    },
    {
      id:18,
      img: "https://m.media-amazon.com/images/I/61N4GyWcHPL.AC_UY575.jpg",
      title: "Classic Bandana Sneakers",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice:14000,
      newPrice: 559,
      company: "Nike",
      color: "black",
      category: "sandals",
      gender:"men",
      quantity:1,
      stock:12
    },
    {
      id:19,
      img: "https://m.media-amazon.com/images/I/61bncQ44yML.AC_UX695.jpg",
      title: "Chunky High Heel",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: 1400,
      newPrice: 456,
      company: "Vans",
      color: "black",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:18
    },
    {
      id:20,
      img: "https://m.media-amazon.com/images/I/71czu7WgGuL.AC_UY695.jpg",
      title: "Slip On Stiletto High Heel",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14000",
      newPrice: 4100,
      company: "puma",
      color: "black",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:13
    },
    {
      id:21,
      img: "https://m.media-amazon.com/images/I/61men05KRxL.AC_UY625.jpg",
      title: "DREAM PAIRS Court Shoes",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: 1400,
      newPrice: "5150",
      company: "Nike",
      color: "red",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:19
      
    },

  
    {
      id:22,
      img: "https://m.media-amazon.com/images/I/51PGWTXgf-L.AC_UY625.jpg",
      title: "Low Mid Block Heels",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: 14999,
      newPrice: 720,
      company: "Nike",
      color: "black",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:13
    },
    {
      id:23,
      img: "https://m.media-amazon.com/images/I/616sA5XUKtL.AC_UY675.jpg",
      title: "Chunky High Heel",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14099",
      newPrice: 825,
      company: "Adidas",
      color: "black",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:15
    },
    {
      id:24,
      img: "https://m.media-amazon.com/images/I/71h5+MbEK7L.AC_UY625.jpg",
      title: "Amore Fashion Stilettos",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14033",
      newPrice: 715,
      company: "Adidas",
      color: "white",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:9
    },
    {
      id:25,
      img: "https://m.media-amazon.com/images/I/61uw5RDxKQL.AC_UY625.jpg",
      title: "Bridal Sandals Glitter",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "14555",
      newPrice:715,
      company: "Adidas",
      color: "black",
      category: "heels",
      gender:"wommen",
      quantity:1,
      stock:16
    },
    {
      id:26,
      img: "https://m.media-amazon.com/images/I/71yhoZP0l6L.AC_UY695.jpg",
      title: "Wedding Prom Bridal",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "5567",
      newPrice:555,
      company: "Adidas",
      color: "black",
      category: "flats",
      gender:"wommen",
      quantity:1,
      stock:11
    },
    {
      id:27,
      img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-shoe/t/i/f/2-yodha-01-asian-original-imags23s9jhwjcws.jpeg?q=70",
      title: "Lace Running Shoes For Boys  ",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(102 reviews)",
      prevPrice: "140667,",
      newPrice:999,
      company: "Adidas",
      color: "black",
      category: "sneakers",
      gender:"kids",
      quantity:1,
      stock:16
    },
    {
      id:28,
      img: "https://rukminim2.flixcart.com/image/832/832/xif0q/kids-shoe/5/d/k/13-sk-97-sparx-original-imagk8x4uatjtah3.jpeg?q=70",
      title: "Velcro Sneakers For Boys",
      star: <AiFillStar className="ratings-start" />,
      reviews: "(123 reviews)",
      prevPrice: "80000",
      newPrice:777,
      company: "Adidas",
      color: "blue",
      category: "sneakers",
      gender:'kids',
      quantity:1,
      stock:20
  
    },
  ]

  export default Product;